const gridData = {
    'common': {
        "fields": [
            {fieldName: 'EID', dataType: 'text'},
            {fieldName: 'EMP_NUMBER', dataType: 'text'},
            {fieldName: 'EMP_NAME', dataType: 'text'},
            {fieldName: 'E_JOIN_DATE', dataType: 'text'},
            {fieldName: 'SI_REGIST_MATTER_NO', dataType: 'text'},
            {fieldName: 'SI_NATIONALITY', dataType: 'text'},
            {fieldName: 'SI_NATIONALITY_NM', dataType: 'text'},
            {fieldName: 'SI_STAY_STATUS', dataType: 'text'},
            {fieldName: 'SI_REP_FLAG', dataType: 'text'},
            {fieldName: 'RRN_ENCRYPT', dataType: 'text'},
            {fieldName: 'ACTION_UPDATE'},
        ],
        "columns": [
            {fieldName: 'EMP_NAME', header: '성명'},
            {fieldName: 'E_JOIN_DATE', header: '입사일'},
            {fieldName: 'RRN_ENCRYPT', header: '주민등록번호'},
            {fieldName: 'SI_NATIONALITY_NM', header: '국적'},
            {fieldName: 'SI_STAY_STATUS', header: '체류자격'},
            {fieldName: 'SI_REP_FLAG', header: '대표자여부'}
        ],
        'url': '/payroll/insurance/regist/common-inf/in-list',
        'modal': 'acquisitionJobCommonInputModal'
    },
    'annual_pension': {
        "fields": [
            {fieldName: 'PEN_SELECT_FL', dataType: 'text'},
            {fieldName: 'EID', dataType: 'text'},
            {fieldName: 'EMP_NUMBER', dataType: 'text'},
            {fieldName: 'EMP_NAME', dataType: 'text'},
            {fieldName: 'SI_REGIST_MATTER_NO', dataType: 'text'},
            {fieldName: 'PEN_MONTHLY_INCOME', dataType: 'number'},
            {fieldName: 'PEN_BEG_MON_FL', dataType: 'text'},
            {fieldName: 'PEN_REGIST_CODE', dataType: 'text'},
            {fieldName: 'PEN_REGIST_CODE_NAME', dataType: 'text'},
            {fieldName: 'PEN_REGIST_DATE', dataType: 'text'},
            {fieldName: 'PEN_SPECIAL_OCCU_CODE', dataType: 'text'},
            {fieldName: 'PEN_OTH_PEN_FL', dataType: 'text'},
            {fieldName: 'ACTION_UPDATE'},
        ],
        "columns": [
            {fieldName: 'PEN_SELECT_FL', header: '신고여부'},
            {fieldName: 'EMP_NAME', header: '성명'},    
            {fieldName: 'PEN_MONTHLY_INCOME', header: '소득월액', numberFormat: "#,##0", styleName: "right-column",
            footer: {
                header: "0",
                expression: "sum",
                numberFormat: "#,##0",
            }, nanText: '0' },    
            {fieldName: 'PEN_BEG_MON_FL', header: '취득월납부여부'},
            {fieldName: 'PEN_REGIST_CODE_NAME', header: '취득부호', width: 150},
            {fieldName: 'PEN_REGIST_DATE', header: '자격취득일'},    
            {fieldName: 'PEN_SPECIAL_OCCU_CODE', header: '특수직종'},    
            {fieldName: 'PEN_OTH_PEN_FL', header: '직역연금부호'},    
        ],
        'url': '/payroll/insurance/regist/pension/list',
        'modal': 'acquisitionJobAnnualInputModal'
    },
    'health': {
        "fields": [
            {fieldName: 'MED_SELECT_FL', dataType: 'text'},
            {fieldName: 'EID', dataType: 'text'},
            {fieldName: 'EMP_NUMBER', dataType: 'text'},
            {fieldName: 'EMP_NAME', dataType: 'text'},
            {fieldName: 'SI_REGIST_MATTER_NO', dataType: 'text'},
            {fieldName: 'MED_WPLACE_CODE', dataType: 'text'},
            {fieldName: 'MED_WPLACE_NAME', dataType: 'text'},
            {fieldName: 'MED_MONTHLY_INCOME', dataType: 'number'},
            {fieldName: 'MED_REGIST_CODE', dataType: 'text'},
            {fieldName: 'MED_REGIST_CODE_NAME', dataType: 'text'},
            {fieldName: 'MED_REGIST_DATE', dataType: 'text'},
            {fieldName: 'MED_REDUCTION', dataType: 'text'},
            {fieldName: 'MED_CARD_DELIVERY_FL', dataType: 'text'},
            {fieldName: 'MED_ACCOUNTING_CODE', dataType: 'text'},
            {fieldName: 'HRDEPT_NAMK', dataType: 'text'},
            {fieldName: 'MED_OCCU_CODE', dataType: 'text'},
            {fieldName: 'ACTION_UPDATE'},
        ],
        "columns": [
            {fieldName: 'MED_SELECT_FL', header: '신고여부'},
            {fieldName: 'EMP_NAME', header: '성명'},    
            {fieldName: 'MED_WPLACE_CODE', header: '단위사업장 기호'},    
            {fieldName: 'MED_WPLACE_NAME', header: '단위사업장 명칭', width: 150},    
            {fieldName: 'MED_MONTHLY_INCOME', header: '보수월액', numberFormat: "#,##0", styleName: "right-column",
            footer: {
                header: "0",
                expression: "sum",
                numberFormat: "#,##0",
            }, nanText: '0' },    
            {fieldName: 'MED_REGIST_CODE_NAME', header: '취득부호'},    
            {fieldName: 'MED_REGIST_DATE', header: '자격취득일'},    
            {fieldName: 'MED_REDUCTION', header: '감면'},    
            {fieldName: 'MED_CARD_DELIVERY_FL', header: '건강보험증 사업장발송여부'},
            {fieldName: 'MED_ACCOUNTING_CODE', header: '회계'},    
            {fieldName: 'MED_OCCU_CODE', header: '직종'},    
        ],
        'url': '/payroll/insurance/regist/med/list',
        'modal': 'acquisitionJobHealthInputModal'
    },
    'employment': {
        "fields": [
            {fieldName: 'EMP_SELECT_FL', dataType: 'text'},
            {fieldName: 'EID', dataType: 'text'},
            {fieldName: 'EMP_NUMBER', dataType: 'text'},
            {fieldName: 'EMP_NAME', dataType: 'text'},
            {fieldName: 'EMP_REGIST_DATE', dataType: 'text'},
            {fieldName: 'SI_REGIST_MATTER_NO', dataType: 'text'},
            {fieldName: 'HRDEPT_NAMK', dataType: 'text'},
            {fieldName: 'EMP_WEEKLY_WORK_HOUR', dataType: 'text'},
            {fieldName: 'EMP_TEMP_CONT_FL', dataType: 'text'},
            {fieldName: 'EMP_TEMP_CONT_EXP_MON', dataType: 'text'},
            {fieldName: 'EMP_MONTHLY_INCOME', dataType: 'number'},
            {fieldName: 'EMP_REMARK', dataType: 'text'},
            {fieldName: 'EMP_ASSESS_CODE', dataType: 'text'},
            {fieldName: 'EMP_ASSESS_REASON', dataType: 'text'},
            {fieldName: 'EMP_OCCU_CODE', dataType: 'text'},
            {fieldName: 'ACTION_UPDATE'}
        ],
        "columns": [
            {fieldName: 'EMP_SELECT_FL', header: '신고여부'},
            {fieldName: 'EMP_NAME', header: '성명'},    
            {fieldName: 'EMP_REGIST_DATE', header: '자격취득일'},    
            {fieldName: 'EMP_OCCU_CODE', header: '직종'},    
            {fieldName: 'EMP_WEEKLY_WORK_HOUR', header: '주소정근로시간'},    
            {fieldName: 'EMP_TEMP_CONT_FL', header: '계약직여부'},
            {fieldName: 'EMP_TEMP_CONT_EXP_MON', header: '계약직종료년월'},    
            {fieldName: 'EMP_MONTHLY_INCOME', header: '월평균보수', numberFormat: "#,##0", styleName: "right-column",
            footer: {
                header: "0",
                expression: "sum",
                numberFormat: "#,##0",
            }, nanText: '0' },    
            {fieldName: 'EMP_REMARK', header: '비고'},
            {fieldName: 'EMP_ASSESS_CODE', header: '보험료부과 구분부호'},    
            {fieldName: 'EMP_ASSESS_REASON', header: '보험료부과 구분사유'},    
        ],
        'url': '/payroll/insurance/regist/emp/list',
        'modal': 'acquisitionJobEmploymentInputModal'
    },
    'industrial_ash': {
        "fields": [
            {fieldName: 'WC_SELECT_FL', dataType: 'text'},
            {fieldName: 'EID', dataType: 'text'},
            {fieldName: 'EMP_NUMBER', dataType: 'text'},  
            {fieldName: 'EMP_NAME', dataType: 'text'},
            {fieldName: 'SI_REGIST_MATTER_NO', dataType: 'text'},
            {fieldName: 'WC_REGIST_DATE', dataType: 'text'},
            {fieldName: 'WC_OCCU_CODE', dataType: 'text'},
            {fieldName: 'WC_WEEKLY_WORK_HOUR', dataType: 'text'},
            {fieldName: 'WC_TEMP_CONT_FL', dataType: 'text'},
            {fieldName: 'WC_TEMP_CONT_EXP_MON', dataType: 'text'},
            {fieldName: 'WC_MONTHLY_INCOME', dataType: 'number'},
            {fieldName: 'WC_REMARK', dataType: 'text'},
            {fieldName: 'WC_ASSESS_CODE', dataType: 'text'},
            {fieldName: 'WC_ASSESS_REASON', dataType: 'text'},
            {fieldName: 'ACTION_UPDATE'}
        ],
        "columns": [
            {fieldName: 'WC_SELECT_FL', header: '신고여부'},
            {fieldName: 'EMP_NAME', header: '성명'},
            {fieldName: 'WC_REGIST_DATE', header: '가격취득일'},
            {fieldName: 'WC_OCCU_CODE', header: '직종'},
            {fieldName: 'WC_WEEKLY_WORK_HOUR', header: '주소정근로시간'},
            {fieldName: 'WC_TEMP_CONT_FL', header: '계약직여부'},
            {fieldName: 'WC_TEMP_CONT_EXP_MON', header: '계약직년월'},
            {fieldName: 'WC_MONTHLY_INCOME', header: '월평균보수', numberFormat: "#,##0", styleName: "right-column",
            footer: {
                header: "0",
                expression: "sum",
                numberFormat: "#,##0",
            }, nanText: '0' },
            {fieldName: 'WC_REMARK', header: '비고'},
            {fieldName: 'WC_ASSESS_CODE', header: '보험료부과 구분부호'},
            {fieldName: 'WC_ASSESS_REASON', header: '보험료부과 구분사유'},
        ],
        'url': '/payroll/insurance/regist/wc/list',
        'modal': 'acquisitionJobIndustrialAshInputModal'
    },
}
export default gridData;